// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pauxdtotvuvlxluhqaye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhdXhkdG90dnV2bHhsdWhxYXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzg3MjksImV4cCI6MjA2MDcxNDcyOX0.b_lf8ddHMIZz6ka5FRdPliN6SX0SWEEbpgTH63XLO3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);